version: "2"
services:
  node:
    image: "node:10"
    user: "node"
    command: "mkdir -p /usr/src/app && chown -R node:node /usr/src/app"
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    expose:
      - "8080"
    command: "npm start index.js"

